apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler-cronjob
  namespace: default 
spec:
  schedule: "*/10 * * * *"  # 매 시간마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: web-crawler
              image: shin1031/web-crawler-go:latest
              envFrom:
                - configMapRef:
                    name: crawler-args-config
                - secretRef:
                    name: db-secret
              args:
                - "$(ARG1)"
                - "$(ARG2)" 
          restartPolicy: OnFailure
      backoffLimit: 3
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 1
