name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t shin1031/web-crawler-go:latest .
        docker push shin1031/web-crawler-go:latest
